# Generated by Django 2.2.5 on 2019-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='human_ques',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
