# Generated by Django 3.0.3 on 2020-04-22 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0002_auto_20190924_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='bot_reply',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='human_ques',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='text',
            field=models.CharField(default=datetime.datetime(2020, 4, 22, 9, 56, 8, 427237, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.CategoryModel')),
            ],
            options={
                'verbose_name': 'Q&A',
                'verbose_name_plural': 'Q&A',
            },
        ),
    ]
