# Generated by Django 3.0.3 on 2020-04-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0003_auto_20200422_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('asked_question', models.TextField()),
                ('answer', models.TextField()),
                ('score', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('actual_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybot.QuestionAnswerModel')),
            ],
            options={
                'verbose_name': 'FeedBackSystem',
                'verbose_name_plural': 'FeedBackSystem',
            },
        ),
    ]
