# Generated by Django 3.0.3 on 2020-04-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0004_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
