# Generated by Django 2.2.12 on 2020-05-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0005_auto_20200422_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'Feedback System', 'verbose_name_plural': 'Feedback System'},
        ),
    ]
