# Generated by Django 2.2.12 on 2020-05-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0006_auto_20200512_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericQuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
    ]
